  
  version: "3.5"
  services:
    docker:
      image: docker
      build: ./postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=test
      healthcheck: 
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 30s
        retries: 3

 